env: "local" # local, dev, prod
http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 60s
  jwt_secret: "top-secret"
database:
  host: "localhost"
  port: 5433
  name: "exptr_db"
  user: "postgres"
  password: "postgres"
