// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	models "alex_gorbunov_exptr_api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CreateOperationHandler is an autogenerated mock type for the CreateOperationHandler type
type CreateOperationHandler struct {
	mock.Mock
}

// CreateOperation provides a mock function with given fields: _a0
func (_m *CreateOperationHandler) CreateOperation(_a0 models.OperationRequest) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.OperationRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCreateOperationHandler creates a new instance of CreateOperationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateOperationHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateOperationHandler {
	mock := &CreateOperationHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
