basePath: /api/v1
definitions:
  models.CreateOperationRequest:
    properties:
      amount:
        type: integer
      category_id:
        type: string
      comment:
        type: string
      created_at:
        type: string
      currency:
        type: string
      name:
        type: string
      type:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    required:
    - amount
    - category_id
    - created_at
    - currency
    - name
    - type
    - user_id
    type: object
  models.CreateOperationResponse:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.LoginResponse:
    properties:
      error:
        type: string
      status:
        type: string
      token:
        type: string
    type: object
  models.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  response.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: algor.monte@gmail.com
    name: Alexander Gorbunov
  description: API for expense tracker project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger EXPTR API
  version: "1.0"
paths:
  /operations/new:
    post:
      consumes:
      - application/json
      description: Create new operation
      parameters:
      - description: Create operation
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.CreateOperationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateOperationResponse'
        "400":
          description: empty request body
          schema:
            type: string
        "500":
          description: server error
          schema:
            type: string
      summary: Create new operation
      tags:
      - operations
  /users/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: login request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: empty request body
          schema:
            type: string
        "404":
          description: wrong email or password
          schema:
            type: string
        "500":
          description: server error
          schema:
            type: string
      summary: Login
      tags:
      - users
  /users/signup:
    post:
      consumes:
      - application/json
      description: Signup
      parameters:
      - description: signup request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: empty request body
          schema:
            type: string
        "404":
          description: user already exists
          schema:
            type: string
        "500":
          description: server error
          schema:
            type: string
      summary: Signup
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
