/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Swagger EXPTR API
 * API for expense tracker project.
 * OpenAPI spec version: 1.0
 */

export interface ModelsCategoryRequest {
  created_at?: string;
  name?: string;
  type?: string;
  updated_at?: string;
  user_id?: string;
}
