/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Swagger EXPTR API
 * API for expense tracker project.
 * OpenAPI spec version: 1.0
 */

export interface ModelsOperationRequest {
  amount: number;
  category_id: string;
  comment?: string;
  created_at: string;
  currency: string;
  name: string;
  type: string;
  updated_at?: string;
  user_id: string;
}
